### ISSUE TITLE
With the current routes, document ids can't contain slashes.

### ISSUE THREAD

**Issue by greg0ire** [sonata-project/SonataDoctrinePhpcrAdminBundle#272]
I tried creating a Document: it's a Film that belongs to a given Category object. I created an `Admin` for this `Film`, and was forced to specify its parent document. I manually entered `/categories/THRILLER` in the input that corresponds to this field. It seems to work : 

```
 bin/console doctrine:phpcr:node:dump --props --identifiers 
ROOT:
  categories:
    - jcr:primaryType = nt:unstructured
    THRILLER:
      - phpcr:classparents = Array()
      - phpcr:class = Cine\DbBundle\Document\Category
      - phpcr_locale:fr-name = Thriller
      - phpcr_locale:en-name = Thriller
      - jcr:mixinTypes = Array(    [0] => phpcr:managed)
      - jcr:primaryType = nt:unstructured
      test(cd68d777-4f97-4a43-9bcc-adaeebb01958):
        - jcr:predecessors = 
         - : b85d82e1-7e4e-4a68-b948-d2f27b8e0c41
        - phpcr:classparents = Array()
        - phpcr:class = Cine\DbBundle\Document\Film
        - jcr:uuid = cd68d777-4f97-4a43-9bcc-adaeebb01958
        - jcr:mixinTypes = Array(    [0] => phpcr:managed    [1] => mix:versionable)
        - jcr:versionHistory = 
         - : 0ddebf9e-f804-4e6c-9320-6f8fb10acc79
        - phpcr_locale:en-summary = test
        - phpcr_locale:en-title = test
        - jcr:baseVersion = 
         - : b85d82e1-7e4e-4a68-b948-d2f27b8e0c41
        - jcr:primaryType = nt:unstructured
        - jcr:isCheckedOut = 1
    COMEDY:
      - phpcr:classparents = Array()
      - phpcr:class = Cine\DbBundle\Document\Category
      - phpcr_locale:fr-name = Comédie
      - phpcr_locale:en-name = Comedy
      - jcr:mixinTypes = Array(    [0] => phpcr:managed)
      - jcr:primaryType = nt:unstructured
```

But the routes I have in my application are not very friendly with ids that contain slashes : 

> Parameter "id" for route "admin_cine_db_film_edit" must match "[^/]++" ("categories/THRILLER/test" given) to generate a corresponding URL. 

Here is the dump for the corresponding route : 

```
[router] Route "admin_cine_db_film_edit"
Name         admin_cine_db_film_edit
Path         /cine/db/film/{id}/edit
Host         ANY
Scheme       ANY
Method       ANY
Class        Symfony\Component\Routing\Route
Defaults     _controller: SonataAdminBundle:CRUD:edit
             _sonata_admin: sonata.admin.film
             _sonata_name: admin_cine_db_film_edit
Requirements 
Options      compiler_class: Symfony\Component\Routing\RouteCompiler
             expose: true
Path-Regex   #^/cine/db/film/(?P<id>[^/]++)/edit$#s
```

How will I be able to create a Film anywhere in the tree if ids can't contain slashes ?
