### ISSUE TITLE
Using ChildAdmin with PHPCR

### ISSUE THREAD

**Issue by he-li** [sonata-project/SonataDoctrinePhpcrAdminBundle#311]
Hello,

In our project, we want to use the functionality of child admin since we have 3 levels of embed form.
We have a top level document **Collection** which can have some **Section**, and each section has some **Item**. Here is the configuration yaml file.

```
Collection:
    ...
    referrers:
        sections:
            referencedBy: collection
            referringDocument: Section

Section:  
    ...  
    referenceMany:
        items:
            strategy: weak
            targetDocument: Item
            cascade: [ all ]
    referenceOne:
        collection:
            strategy: hard
            targetDocument: Collection

Item
    ...
    referrers:
        section:
            referencedBy: items
            referringDocument: Section
```

We met 2 problems when we tried to declare parentAssociationMapping(=collection) in sectionAdmin.
1.   It's not possible to use id(path) of document in routing. Because a URL like this /collection/{id}/section/{childId} cannot work with a document path. I have to overwrite the following methods to use uuid instead of id
   
   ```
   /**
    * {@inheritdoc}
    */
   public function generateObjectUrl($name, $object, array $parameters = array(), $absolute = false)
   {
       // use uuid instead of path
       $parameters['id'] = $object->getUuid();
   
       return $this->generateUrl($name, $parameters, $absolute);
   }
   
   /**
    * {@inheritdoc}
    */
   public function getObject($id)
   {
       // find object by uuid instead of id
       $object = $this->getModelManager()->find(null, $id);
       foreach ($this->getExtensions() as $extension) {
           $extension->alterObject($this, $object);
       }
   
       return $object;
   }
   ```
2.   There's no filter type for relations.  I don't find a better solution, but use doctrine_phpcr_callback in my datagrid element
   
   ![error](https://cloud.githubusercontent.com/assets/7941350/5067771/adbaaf16-6e46-11e4-9247-955ab316593e.jpg)
   
   ```
       $datagridMapper
           ->add(
               'collection',
               'doctrine_phpcr_callback',
               array(
                   'callback' => function ($proxyQuery, $alias, $field, $data) {
                           ...
                           return true;
                       },
               )
           );
   ```

So what do you think of the solution? And will the childAdmin feature be integrated in the bundle soon?

Thanks
